description: |-
  OpenFluid deployment (GPU)
chart: http://vm039.elijah.cs.cmu.edu:81/openfluid/openfluid
version: 1.0.0
values:
  fullnameOverride: openfluid
  runtimeClassName: nvidia
  resources:
    limits:
      nvidia.com/gpu: 1
restricted: false

