# Default values for openfluid-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# GPUs need the appropriate device-plugin support enabled in the cluster
# https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/
# and their dependency/use needs to be declared under "resources: limits: ..."

replicaCount: 1

image:
  repository: ghcr.io/cmusatyalab/openfluid
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: test-driver525

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Having some trouble where nvidia-container-toolkit fails to
# set the default runtime class for k3s containerd.
#
# So if you want to use the gpu, specify both
#
# runtimeClassName: "nvidia"
# resources:
#   limits:
#     nvidia.com/gpu: 1

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9099

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  #  nvidia.com/gpu: 1
  #  gpu.intel.com/i915: 1
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
