version: '1.0'
services:
  openfluid:
    image: ghcr.io/cmusatyalab/openfluid:test-driver470
    # build: .
    container_name: openfluid-server
    privileged: true
    devices:
      - "/dev/dri:/dev/dri"
    ports:
      - "9099:9099"
    restart: unless-stopped

    # for NVIDIA GPUs
    # gpus: all     # not yet supported by docker-compose
    runtime: nvidia

