# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openfluid.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fopenfluid.proto\x12\topenfluid\"\x92\x06\n\x06\x45xtras\x12\x34\n\nstyle_list\x18\x01 \x03(\x0b\x32 .openfluid.Extras.StyleListEntry\x12-\n\timu_value\x18\x02 \x01(\x0b\x32\x1a.openfluid.Extras.IMUValue\x12\x33\n\x0cscreen_value\x18\x03 \x01(\x0b\x32\x1d.openfluid.Extras.ScreenValue\x12\x31\n\x0btouch_value\x18\x04 \x01(\x0b\x32\x1c.openfluid.Extras.TouchInput\x12-\n\tarrow_key\x18\x05 \x01(\x0b\x32\x1a.openfluid.Extras.ArrowKey\x12\x30\n\rsetting_value\x18\x06 \x01(\x0b\x32\x19.openfluid.Extras.Setting\x12\x15\n\rlatency_token\x18\x07 \x01(\x05\x12\x0b\n\x03\x66ps\x18\x08 \x01(\x05\x1a\x1b\n\nBytesValue\x12\r\n\x05value\x18\x01 \x01(\x0c\x1a+\n\x08IMUValue\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x1a\x46\n\nTouchInput\x12\r\n\x05scale\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\x13\n\x0b\x64oubleTouch\x18\x04 \x01(\x08\x1a\x30\n\x0bScreenValue\x12\r\n\x05ratio\x18\x01 \x01(\x02\x12\x12\n\nresolution\x18\x02 \x01(\x05\x1a\x41\n\x08\x41rrowKey\x12\x0c\n\x04left\x18\x01 \x01(\x08\x12\r\n\x05right\x18\x02 \x01(\x08\x12\n\n\x02up\x18\x03 \x01(\x08\x12\x0c\n\x04\x64own\x18\x04 \x01(\x08\x1a}\n\x07Setting\x12\r\n\x05scene\x18\x01 \x01(\x05\x12\x14\n\x0c\x61lign_center\x18\x02 \x01(\x08\x12\x0f\n\x07\x61r_view\x18\x03 \x01(\x08\x12\r\n\x05reset\x18\x04 \x01(\x08\x12\r\n\x05pause\x18\x05 \x01(\x08\x12\x10\n\x08particle\x18\x06 \x01(\x08\x12\x0c\n\x04info\x18\x07 \x01(\x08\x1a\x30\n\x0eStyleListEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x1e\n\x14\x65\x64u.cmu.cs.openfluidB\x06Protosb\x06proto3')



_EXTRAS = DESCRIPTOR.message_types_by_name['Extras']
_EXTRAS_BYTESVALUE = _EXTRAS.nested_types_by_name['BytesValue']
_EXTRAS_IMUVALUE = _EXTRAS.nested_types_by_name['IMUValue']
_EXTRAS_TOUCHINPUT = _EXTRAS.nested_types_by_name['TouchInput']
_EXTRAS_SCREENVALUE = _EXTRAS.nested_types_by_name['ScreenValue']
_EXTRAS_ARROWKEY = _EXTRAS.nested_types_by_name['ArrowKey']
_EXTRAS_SETTING = _EXTRAS.nested_types_by_name['Setting']
_EXTRAS_STYLELISTENTRY = _EXTRAS.nested_types_by_name['StyleListEntry']
Extras = _reflection.GeneratedProtocolMessageType('Extras', (_message.Message,), {

  'BytesValue' : _reflection.GeneratedProtocolMessageType('BytesValue', (_message.Message,), {
    'DESCRIPTOR' : _EXTRAS_BYTESVALUE,
    '__module__' : 'openfluid_pb2'
    # @@protoc_insertion_point(class_scope:openfluid.Extras.BytesValue)
    })
  ,

  'IMUValue' : _reflection.GeneratedProtocolMessageType('IMUValue', (_message.Message,), {
    'DESCRIPTOR' : _EXTRAS_IMUVALUE,
    '__module__' : 'openfluid_pb2'
    # @@protoc_insertion_point(class_scope:openfluid.Extras.IMUValue)
    })
  ,

  'TouchInput' : _reflection.GeneratedProtocolMessageType('TouchInput', (_message.Message,), {
    'DESCRIPTOR' : _EXTRAS_TOUCHINPUT,
    '__module__' : 'openfluid_pb2'
    # @@protoc_insertion_point(class_scope:openfluid.Extras.TouchInput)
    })
  ,

  'ScreenValue' : _reflection.GeneratedProtocolMessageType('ScreenValue', (_message.Message,), {
    'DESCRIPTOR' : _EXTRAS_SCREENVALUE,
    '__module__' : 'openfluid_pb2'
    # @@protoc_insertion_point(class_scope:openfluid.Extras.ScreenValue)
    })
  ,

  'ArrowKey' : _reflection.GeneratedProtocolMessageType('ArrowKey', (_message.Message,), {
    'DESCRIPTOR' : _EXTRAS_ARROWKEY,
    '__module__' : 'openfluid_pb2'
    # @@protoc_insertion_point(class_scope:openfluid.Extras.ArrowKey)
    })
  ,

  'Setting' : _reflection.GeneratedProtocolMessageType('Setting', (_message.Message,), {
    'DESCRIPTOR' : _EXTRAS_SETTING,
    '__module__' : 'openfluid_pb2'
    # @@protoc_insertion_point(class_scope:openfluid.Extras.Setting)
    })
  ,

  'StyleListEntry' : _reflection.GeneratedProtocolMessageType('StyleListEntry', (_message.Message,), {
    'DESCRIPTOR' : _EXTRAS_STYLELISTENTRY,
    '__module__' : 'openfluid_pb2'
    # @@protoc_insertion_point(class_scope:openfluid.Extras.StyleListEntry)
    })
  ,
  'DESCRIPTOR' : _EXTRAS,
  '__module__' : 'openfluid_pb2'
  # @@protoc_insertion_point(class_scope:openfluid.Extras)
  })
_sym_db.RegisterMessage(Extras)
_sym_db.RegisterMessage(Extras.BytesValue)
_sym_db.RegisterMessage(Extras.IMUValue)
_sym_db.RegisterMessage(Extras.TouchInput)
_sym_db.RegisterMessage(Extras.ScreenValue)
_sym_db.RegisterMessage(Extras.ArrowKey)
_sym_db.RegisterMessage(Extras.Setting)
_sym_db.RegisterMessage(Extras.StyleListEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024edu.cmu.cs.openfluidB\006Protos'
  _EXTRAS_STYLELISTENTRY._options = None
  _EXTRAS_STYLELISTENTRY._serialized_options = b'8\001'
  _EXTRAS._serialized_start=31
  _EXTRAS._serialized_end=817
  _EXTRAS_BYTESVALUE._serialized_start=379
  _EXTRAS_BYTESVALUE._serialized_end=406
  _EXTRAS_IMUVALUE._serialized_start=408
  _EXTRAS_IMUVALUE._serialized_end=451
  _EXTRAS_TOUCHINPUT._serialized_start=453
  _EXTRAS_TOUCHINPUT._serialized_end=523
  _EXTRAS_SCREENVALUE._serialized_start=525
  _EXTRAS_SCREENVALUE._serialized_end=573
  _EXTRAS_ARROWKEY._serialized_start=575
  _EXTRAS_ARROWKEY._serialized_end=640
  _EXTRAS_SETTING._serialized_start=642
  _EXTRAS_SETTING._serialized_end=767
  _EXTRAS_STYLELISTENTRY._serialized_start=769
  _EXTRAS_STYLELISTENTRY._serialized_end=817
# @@protoc_insertion_point(module_scope)
